# コマンド
# 作成、アップデート
# aws cloudformation deploy --stack-name ec2-instance-create --template-file ./metadata-interface.yml
# 削除
# aws cloudformation delete-stack --stack-name ec2-instance-create

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DevKeyName:
    Description: key name
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    Description: environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must be development or production
  InstanceType:
    Description: Select the ec2 instance type
    Type: String
    Default: t3.nano
    AllowedValues:
      - t3.nano
      - t3.micro
  AvailabilityZone:
    Description: select the availability zone
    Type: String
    Default: ap-northeast-1
    AllowedValues:
      - ap-northeast-1
      - ap-northeast-3

Conditions:
  CreateEIPForProd: !Equals [!Ref environmentName, prod]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - label:
          default: "EC2 Instance Configuration"
        Parameters:
          - InstanceType
          - KeyName
          - AvailabilityZone
      - Label:
          default: "Environment Configuration"
        Parameters:
          - EnvironmentName
    ParameterLabels:
      EnvironmentName:
        default: "Which environment we are planning to create this instance?"
      KeyName:
        defualt: "Be aware that once keyname is selected we cannot change it"

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref DevKeyName
      ImageId: ami-0f27d081df46f326c
      InstanceType: !Ref InstanceType
      Monitoring: true
      Tags:
        - Key: Name
          Value: tf-demo
  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Propertioes:
      InstanceId: !Ref MyEC2Instance
