# コマンド
# 作成、アップデート
# aws cloudformation deploy --stack-name ec2-instance-create --template-file ./ec2-instance-add-new-security-rule.yml
# 削除
# aws cloudformation delete-stack --stack-name ec2-instance-create

AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: tf-demo
      # 2021/03/12時点の最新 Amazon Linux2 x64
      ImageId: ami-0f27d081df46f326c
      InstanceType: t3.nano
      Monitoring: true
      SecurityGroups:
        - default
        - !Ref BasicSecurityGroup
      Tags:
        - Key: Name
          Value: tf-demo

  BasicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: basic-sg
      GroupDescription: My new SSH & HTTP Security Group
      # VpcId:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
