# コマンド
# 作成、アップデート
# aws cloudformation deploy --stack-name ec2-instance-create --template-file ./ec2-instance-create.yml
# 削除
# aws cloudformation delete-stack --stack-name ec2-instance-create

AWSTemplateFormatVersion: 2010-09-09

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: tf-demo
      # 2021/03/12時点の最新 Amazon Linux2 x64
      ImageId: ami-0f27d081df46f326c
      InstanceType: t3.nano
      Monitoring: true
      Tags:
        - Key: Name
          Value: tf-demo
